$(document).ready(function(){
  $("#button").click(function(){
$("#button").hide('1500');
$("#cut").slideDown(2000);
$("#buton").show();
$("#form").hide();
  }
)})
$(document).ready(function(){
  $("#buton").click(function(){
    $("#buton").hide();
    $("#button").show();
    $("#cut").slideUp(2000);
    $("#form").show();
    event.preventDefault();
    
  })
})
$(document).ready(function(){
  $("#butto").click(function(){
    $("#ghana").fadeOut(2000).hide(2000);
    event.preventDefault();
    $("#akan").slideUp(2000).show(2000);
  })
})
